name: Build IPQ807x NSS WiFi for devices

on:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare build environment
    runs-on: self-hosted
    steps:
      - name: 'Cleanup build folder'
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clone AgustinLorenzo openwrt for IPQ807x
        run: |
          git clone --branch custom_main_nss https://github.com/aywl1207/openwrt-ipq807x.git openwrt-ipq807x
      - name: Move openwrt files to root
        run: mv openwrt-ipq807x/* .
      - name: Clean up temporary folder
        run: rm -rf openwrt-ipq807x
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Update latest luci-app-smartdns
        run: |
          rm -rf feeds/luci/applications/luci-app-smartdns/*
          git clone --branch master https://github.com/pymumu/luci-app-smartdns.git feeds/luci/applications/luci-app-smartdns/
          ./scripts/feeds install -a
      - name: Import full config for IPQ807x NSS
        run: cp -f .full_custom_config .config
      - name: QoL fixes on default config
        run: |
          mkdir -p files/etc/uci-defaults
          cat > files/etc/uci-defaults/99-qol_fixes << 'EOF'
          uci set wireless.radio0.country='US'
          uci set wireless.radio1.country='US'
          uci set wireless.radio2.country='US'
          uci set wireless.radio1.disabled=0
          uci set wireless.radio2.disabled=0
          uci set pbuf.opt.memory_profile=auto
          uci set firewall.@defaults[0].flow_offloading=0
          uci set firewall.@defaults[0].flow_offloading_hw=0
          uci set ecm.@general[0].enable_bridge_filtering=0
          uci set system.@system[0].cronloglevel='7'
          /etc/init.d/sqm stop
          /etc/init.d/sqm disable
          uci commit
          EOF
      - name: Ensure permissions for custom script
        run: chmod +x files/etc/uci-defaults/99-qol_fixes

  download:
    name: Download package sources
    runs-on: self-hosted
    needs: prepare
    steps:
      - name: Download package sources
        run: make download -j$(nproc) V=s || make download V=s

  build_tools:
    name: Build tools
    runs-on: self-hosted
    needs: download
    steps:
      - name: Build tools
        run: make tools/install -j$(nproc) V=s || make tools/install V=s

  build_toolchain:
    name: Build toolchain
    runs-on: self-hosted
    needs: build_tools
    steps:
      - name: Build toolchain
        run: make toolchain/install -j$(nproc) V=s || make toolchain/install V=s

  build_images:
    name: Build target images
    runs-on: self-hosted
    needs: build_toolchain
    steps:
      - name: Build target images
        run: make -j$(nproc) V=s || make V=s

  release:
    name: Create release
    runs-on: self-hosted
    needs: build_images
    steps:
      - name: Get the current date
        run: echo "NOW=$(date +%F-%H%M)" >> $GITHUB_ENV
      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.NOW }} | Updated custom prebuilt images for devices (NSS-WiFi)"
          commit: "main"
          tag: "ipq807x-nsswifi-${{ env.NOW }}"
          generateReleaseNotes: true
          makeLatest: true
          artifacts: bin/targets/qualcommax/ipq807x/*
          token: "${{ secrets.GITHUB_TOKEN }}"
